export const POPULAR_CATEGORIES_REQUEST = 'POPULAR_CATEGORIES_REQUEST';
export const POPULAR_CATEGORIES_SUCCESS = 'POPULAR_CATEGORIES_SUCCESS';
export const POPULAR_CATEGORIES_FAILURE = 'POPULAR_CATEGORIES_FAILURE'; 